---

- name: gather state of python virtualenv tarball
  stat: path={{ trackmap_home }}/{{ virtualenv_tarball }}
  register: virtualenv_tarball_st
  ignore_errors: True
  tags:
    - installvirtualenv

- name: ensure virtualenv tarball downloaded
  get_url: >
    url={{ virtualenv_tarball_url }}
    dest={{ trackmap_home }}
    mode=0600
  when: virtualenv_tarball_st.stat.exist is not defined
  tags:
    - installvirtualenv

- name: gather state of virtualenv tarball gpg signature
  stat: path={{ trackmap_home }}/{{ virtualenv_tarball }}.asc
  register: virtualenv_tarball_sig_st
  tags:
    - installvirtualenv

- name: ensure virtualenv tarball gpg signature downloaded
  get_url: >
    url={{ virtualenv_tarball_url }}.asc
    dest={{ trackmap_home }}
    mode=0600
  when: virtualenv_tarball_sig_st.stat.exist is not defined
  tags:
    - installvirtualenv

- name: "check state of Donald Stufft's key in our gpg keyring"
  command: gpg --fingerprint 3372DCFA
  register: virtualenv_key_state
  ignore_errors: True
  tags:
    - installvirtualenv

- name: ensure local copy of virtualenv signing key is present
  copy: >
    src=virtualenv-signing-key.pub
    dest={{ trackmap_home }}/virtualenv-signing-key.pub
  when: virtualenv_key_state|failed
  tags:
    - installvirtualenv

- name: ensure virtualenv signing key is installed
  command: gpg --import virtualenv-signing-key.pub
  when: virtualenv_key_state|failed
  tags:
    - installvirtualenv

- name: gpg verify the python virtualenv tarball
  command: gpg --verify {{ virtualenv_tarball }}.asc
  register: virtualenv_verified
  tags:
    - installvirtualenv

- name: assert that virtualenv tarball is verified
  assert:
    that: "virtualenv_verified.rc == 0"
  tags:
    - installvirtualenv

- name: gather state of virtualenv tarball dir
  stat: path={{ trackmap_home }}/{{ virtualenv_dir }}
  register: virtualenv_tarball_dir_st
  tags:
    - installvirtualenv

- name: ensure python virtualenv tarball extracted
  command: tar xf {{ trackmap_home }}/{{ virtualenv_tarball }} --directory {{ trackmap_home }}
  when: virtualenv_tarball_dir_st.stat.isdir is not defined
  tags:
    - installvirtualenv

- name: gather state of virtualenv target dir
  stat: path="{{ trackmap_home }}/{{ trackmap_virtualenv }}"
  register: virtualenv_st
  tags:
    - installvirtualenv


