---

- include: setup_phantom.yml

- include: setup_ssh_hs.yml 
  when: setup_ssh_hs is defined and setup_ssh_hs

- include: install_virtualenv.yml

- include: setup_trackmap.yml

- include: run_topology.yml
