---

- name: run topology test
  shell: "python topology_tests.py {{ ip_to_test }}"
  args:
    chdir: "{{ trackmap_home }}/{{ trackmap_dir }}/"
  environment: 
    VIRTUAL_ENV: "{{ trackmap_home }}/{{ trackmap_virtualenv }}"
    PATH: "{{ trackmap_home }}/{{ trackmap_virtualenv }}/bin:{{ ansible_env.PATH }}"
#  tags:
#    - runtopology

## probably want to add
# ./perform_analysis.py verified_media/NAME_OF_YOUR_COUNTRY


#FIXME: replace with "{{ lookup('file', '{{hs_dir}}/hostname') }}"              
- name: get ssh hs hostname                                                     
  sudo: true                                                                    
  shell: /bin/cat {{hs_dir}}/hostname                                          
  register: hostname                                                            
  tags:                                                                         
    - runtopology                                                               
                                                                                
- name: notify hostname
  shell: "echo MAIL to trackmap@tacticaltech.org to notify your cooperation and tell this: {{ hostname.stdout }}"
  tags:                                                                         
    - runtopology        
