---
- name: install required packages
  sudo: true
  apt: 
    pkg={{ item }}
    state=latest
    install_recommends=no
  with_items:
    - ca-certificates # for downloading phantom
    - coreutils # for sha224sum 
    - tar
    - bzip2
  tags:
    - setupphantom

# sha will be only verified if downloaded again
# it will only be download again if the file does not exist
- name: ensure phantom is downloaded
  get_url: >
    url={{ phantom_tarball_url }}
    dest={{ trackmap_home }}/{{ phantom_tarball }}
    mode=600
    sha256sum={{ phantom_sha256sum }}
  tags:
    - setupphantom

- name: gather state of phantom tarball dir
  stat: path={{ trackmap_home }}/{{ phantom_dir }}
  register: phantom_tarball_dir_st
  tags:
    - setupphantom

- name: ensure phantom tarball extracted
  command: tar xfj {{ trackmap_home }}/{{ phantom_tarball }} --directory {{ trackmap_home }}
  when: phantom_tarball_dir_st.stat.isdir is not defined
  tags:
    - setupphantom

