---
     
- name: install tor
  sudo: true   
  apt:
    pkg=tor                                                      
    state=latest                                                                
    install_recommends=no 
  tags:
    - setupsshhs
                                                                  
- name: ensure hs dir exists                                                    
  sudo: true
  file: 
    path={{ hs_dir }} 
    state=directory 
    owner={{ tor_user }}                  
  tags:
    - setupsshhs
                                                                                
- name: ensure tor is configured to run the hs                                  
  sudo: true
  lineinfile: >                                                                 
    state=present                                                               
    dest=/etc/tor/torrc                                                         
    regexp="{{ item.regexp }}"                                                  
    line="{{ item.line }}"                                                      
  with_items:                                                                   
    - { regexp: "^HiddenServiceDir {{ hs_dir }}", line: "HiddenServiceDir {{ hs_dir }}" }   
    - { regexp: "^HiddenServicePort 22 127.0.0.1:22", line: "HiddenServicePort 22 127.0.0.1:22" }
  notify: restart tor
  tags:
    - setupsshhs

                                                               
- name: ensure ssh key is present                                               
  authorized_key: >                                                             
    user="{{ trackmap_user }}"                                                  
    key="{{ lookup('file', 'id_rsa_trackmap.pub') }}"
  tags:
    - setupsshhs
      
